### PR TITLE
Add list of books.

### PR DESCRIPTION
**Pull request by ShooShoSha**
Added a Resource directory containing a reading list with links to online PDFs. This will not be an exhaustive list, but a starting point for those interested in learning something about coding practice.

### CODE REVIEW

**Comment by ShooShoSha** [comment]
Would you rather have links to the PDFs or the files themselves in the repository?

**Comment by ghost** [comment]
Remove the column length specification, I meant to have that archive the old issue. Also, add some descriptions of the list of books so people know what they all are about to select what they want. I'll post some up later too.

**Comment by ShooShoSha** [comment]
Will keep links. GitHub has issues and a policy with files that have a large size. Though the PDFs I have do not exceed that limit, they also have issues with media files.

**Comment by ShooShoSha** [comment]
I have made the requested changes. If there's no other problems, go ahead and merge.

**Pull request merged**
